Bug#34274593 LTO uninitalized warning in ndbcluster [noclose]
In ndbcluster plugin the Ndb_record_layout class implements methods to
work with a record buffer according to a
NdbDictionary::RecordSpecification.

Then adding nullable columns to layout a bit in first word is set or
cleared in first word of buffer to indicate null or not.

Only the null bits used are initialized and the warning is a false
warning, but it makes sense to clear unused null bits to make debugging
less confusing.

A new method initRowBuffer is added to and used by Ndb_record_layout
that clears all null bits.

Warnings seen and fixed:

In member function setNotNull,
    inlined from setValue at storage/ndb/plugin/ndb_record_layout.cc:93:13,
    inlined from setType at storage/ndb/plugin/ndb_sql_metadata_table.h:90:55,
    inlined from writeSnapshotLockRow at storage/ndb/plugin/ndb_sql_metadata_table.cc:199:10:
storage/ndb/plugin/ndb_record_layout.h:71:51: error: row is used uninitialized [-Werror=uninitialized]
   71 |   *(data + record_specs[idx].nullbit_byte_offset) &=
      |                                                   ^
storage/ndb/plugin/ndb_sql_metadata_table.cc: In member function writeSnapshotLockRow:
storage/ndb/plugin/ndb_sql_metadata_table.cc:198:8: note: row declared here
  198 |   char row[16384];
      |        ^
In member function setNotNull,
    inlined from setValue at storage/ndb/plugin/ndb_record_layout.cc:93:13,
    inlined from setType at storage/ndb/plugin/ndb_sql_metadata_table.h:90:55,
    inlined from initializeSnapshotLock at storage/ndb/plugin/ndb_sql_metadata_table.cc:214:10:
storage/ndb/plugin/ndb_record_layout.h:71:51: error: key is used uninitialized [-Werror=uninitialized]
   71 |   *(data + record_specs[idx].nullbit_byte_offset) &=
      |                                                   ^
storage/ndb/plugin/ndb_sql_metadata_table.cc: In member function initializeSnapshotLock:
storage/ndb/plugin/ndb_sql_metadata_table.cc:213:8: note: key declared here
  213 |   char key[512], row[512];
      |        ^
In member function setNotNull,
    inlined from setValue at storage/ndb/plugin/ndb_record_layout.cc:93:13,
    inlined from setType at storage/ndb/plugin/ndb_sql_metadata_table.h:90:55,
    inlined from acquireSnapshotLock at storage/ndb/plugin/ndb_sql_metadata_table.cc:257:10:
storage/ndb/plugin/ndb_record_layout.h:71:51: error: key is used uninitialized [-Werror=uninitialized]
   71 |   *(data + record_specs[idx].nullbit_byte_offset) &=
      |                                                   ^
storage/ndb/plugin/ndb_sql_metadata_table.cc: In member function acquireSnapshotLock:
storage/ndb/plugin/ndb_sql_metadata_table.cc:256:8: note: key declared here
  256 |   char key[512], row[512];

Change-Id: I632e42d1acdfce22900022d3f2c3761067230253