WL#9850 MySQL GCS: Change XCom interface to queues instead of sockets
Post-push fix due to Clang warnings:

.../gcs_xcom_input_queue.h:250:13: error: 'static' function 'do_not_reply' declared in header file should be declared 'static inline' [-Werror,-Wunneeded-internal-declaration]
static void do_not_reply(void *reply, pax_msg *payload) {
            ^
.../gcs_xcom_input_queue.h:255:13: error: 'static' function 'reply_by_resolving_future' declared in header file should be declared 'static inline' [-Werror,-Wunneeded-internal-declaration]
static void reply_by_resolving_future(void *reply, pax_msg *payload) {
            ^
2 errors generated.