WL#12771 reuse connection [26/26] - integration test
Post-push fix:
mysql_client.h:51:19: error:
'static' function 'make_mysql_error_code' declared in header
file should be declared 'static inline'

Change-Id: Ideef6f65a2bf9727449137bcf17f58d0e01215cc
(cherry picked from commit 0c41b242824fbdbec25ee80ca3c57f1fa7e7c65a)