Bug #34311325 Fix linker flags for clang/ubsan
The patch for
  Bug #27135504 UBSAN: BOOST - DETERMINANT.HPP - SIGNED INTEGER OVERFLOW
added a workaround for clang bug
  https://bugs.llvm.org/show_bug.cgi?id=16404

"clang fails to link code which does a multiply of two int128_t
 variables on x86_64 if the code is compiled with -fsanitize=undefined
 : it fails with "undefined reference to '__muloti4'. The same code
 compiles OK if the -fsanitize argument is omitted."

The patch fixed only CMAKE_EXE_LINKER_FLAGS.
Fix CMAKE_MODULE_LINKER_FLAGS and CMAKE_SHARED_LINKER_FLAGS also.
Also fix it for all config types, not just DEBUG and RELWITHDEBINFO.

Change-Id: Iea3497f413e235273f2b5e02a03d596581f53b2b