Bug #26826272: REMOVE GCC 8 WARNINGS
Post-push fix for UNIV_MEM_TRASH which is use for WITH_VALGRIND build.

Same as TRASH macro: do memset through a void pointer to avoid
error: 'void* memset(void*, int, size_t)'
writing to an object of type 'struct buf_buddy_free_t'
with no trivial copy-assignment [-Werror=class-memaccess]

Change-Id: I90b1ca37c3906a71ed39f2feb71ae01bd5396a91