Bug #24466419: WARNINGS WITH GCC 7.0 PRERELEASE
Most of these are about debugging code and asserts, but there's also one
case of genuinely invalid type-punning code.

Fixed warnings (some duplicates have been removed):

../regex/main.c: In function 'eprint':
../regex/main.c:564:9: error: variable 'len' set but not used [-Werror=unused-but-set-variable]
  size_t len;

../unittest/gunit/components/mysql_server/dynamic_loader-t.cc:96:10: error: suggest explicit braces to avoid ambiguous 'else' [-Werror=dangling-else]
       if (reg)

../sql/sql_partition.cc:7690:47: error: 'get_col_endpoint' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     part_iter->part_nums.end= get_col_endpoint(part_info, FALSE,
                               ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
                                                !(flags & NEAR_MAX),
                                                ~~~~~~~~~~~~~~~~~~~~
                                                nparts);
                                                ~~~~~~~
../client/mysqltest.cc:9043:10: error: unused variable 'len' [-Werror=unused-variable]
   size_t len= my_regerror(MY_REG_ITOA | err, NULL, epbuf, sizeof(epbuf));

../unittest/gunit/gis_algos-t.cc:335:47: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   plgn5.outer() = *((Gis_polygon_ring *)(&ls8));

Change-Id: I8600f7b117acea8ecb4c38c613ce1fa28a6f71bd