WL#12413: Move mysql_upgrade client actions into the server
Post-push fix: add missing dependency.

In a clean build: 'make sql_dd'
sql/dd/impl/upgrade/server.cc:36:10:
fatal error: scripts/mysql_fix_privilege_tables_sql.c: No such file or directory
 #include "scripts/mysql_fix_privilege_tables_sql.c"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: Iab342b1be2c9d418e6343ebbaaba00a81ccca79a