WL#13601 Deprecate arbitrary delimiters and whitespaces in time/date/datetime/timestamp literals
Post-push fixes:

- The row numbers in some of the deprecation warnings varied depending
on which optimizer was used. Filter out the row numbers in the
problematic query.

- Clang gave the following warning:

my_time.h:202:22: error: definition of implicit copy constructor for
'MYSQL_TIME_STATUS' is deprecated because it has a user-provided copy
assignment operator [-Werror,-Wdeprecated-copy-with-user-provided-copy]

Fixed by declaring the automatically generated constructors
explicitly.

Change-Id: Ide5f69f0591c9259c89e0be0d01db77f8eae5107