Bug #33108847 BROKEN BUILD FOR BUNDLED LIBFIDO WITH PGO/LTO
With PGO/LTO enabled, the bundled libfido2 build is broken.  We
normally do not build, or run, the authentication plugins when doing
profile-guided optimizations.

It should still be possible to build and run them, so add a call to
the macro DISABLE_MISSING_PROFILE_WARNING.

Move DISABLE_MISSING_PROFILE_WARNING from maintainer.cmake to the top
level CMakeLists.txt so that it can be used without adding all the
other stuff in maintainer.cmake.

Also fix:
extra/libfido2/openbsd-compat/openbsd-compat.h:71:5:
error: "OPENSSL_VERSION_NUMBER" is not defined

Change-Id: I123833845690fa1dcf30733630a4d7c7ee167f86
(cherry picked from commit 5fd5019f8c524580f77931807aa6817bdba221a0)