PXB-3139: Fix gcc-13 and clang-16 compilation issues
Fix the following issues:
1.
```
/data/percona-xtrabackup/8.0/storage/innobase/xtrabackup/src/keyring_plugins.cc:191:35: error: 'sizeof (TRANSITION_KEY_PREFIX)' will return the size of the pointer, not the array itself [-Werror,-Wsizeof-pointer-div]
    sizeof(TRANSITION_KEY_PREFIX) / sizeof(char);
```
2. All files that use `UT_NEW_THIS_FILE_PSI_KEY` should be added to `auto_event_names` in auto_event_names in `storage/innobase/include/ut0new.h` because in another case we have:
```
/data/percona-xtrabackup/8.0/storage/innobase/xtrabackup/src/backup_copy.cc:440:74: error: array index -1 is before the beginning of the array [-Werror,-Warray-bounds]
  data_threads = (datadir_thread_ctxt_t *)(ut::malloc_withkey(UT_NEW_THIS_FILE_PSI_KEY, length));
                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~
/data/percona-xtrabackup/8.0/storage/innobase/include/ut0new.h:566:34: note: expanded from macro 'UT_NEW_THIS_FILE_PSI_KEY'
       : ut::make_psi_memory_key(auto_event_keys[UT_NEW_THIS_FILE_PSI_INDEX]))
                                 ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/percona-xtrabackup/8.0/storage/innobase/include/ut0new.h:447:1: note: array 'auto_event_keys' declared here
extern PSI_memory_key auto_event_keys[n_auto];
```

3. Add `#include <cstdint>` to fix:
```
/data/percona-xtrabackup/8.0/components/keyrings/common/data/data.h:69:24: error: no member named 'uintptr_t' in namespace 'std'
        std::hash<std::uintptr_t>{}(reinterpret_cast<std::uintptr_t>(this));
                  ~~~~~^
/data/percona-xtrabackup/8.0/components/keyrings/common/data/data.h:69:54: error: no type named 'uintptr_t' in namespace 'std'; did you mean simply 'uintptr_t'?
        std::hash<std::uintptr_t>{}(reinterpret_cast<std::uintptr_t>(this));
                                                     ^~~~~~~~~~~~~~
                                                     uintptr_t
```

4. Port fixes from Percona Server related to "not marked 'override'" e.g.:
```
In file included from /data/percona-xtrabackup/8.0/plugin/keyring/common/keys_container.cc:30:
/data/percona-xtrabackup/8.0/plugin/keyring/common/system_keys_container.h:41:3: error: '~System_keys_container' overrides a destructor but is not marked 'override' [-Werror,-Winconsistent-missing-destructor-override]
  ~System_keys_container();
  ^
/data/percona-xtrabackup/8.0/plugin/keyring/common/i_system_keys_container.h:30:11: note: overridden virtual function is here
  virtual ~ISystem_keys_container() {}
```

5. Port fixes from Percona Server related to "shadows member inherited from" e.g.:
```
/data/percona-xtrabackup/8.0/plugin/keyring_vault/vault_keys_container.h:30:33: error: parameter 'logger' shadows member inherited from type 'Keys_container' [-Werror,-Wshadow-field]
  Vault_keys_container(ILogger *logger) noexcept : Keys_container(logger) {}
```

6.
```
/data/percona-xtrabackup/8.0/plugin/keyring/common/keyring_memory.h:63:3: error: definition of implicit copy assignment operator for 'Secure_allocator<char>' is deprecated because it has a user-provided copy constructor [-Werror,-Wdeprecated-copy-with-user-provided-copy]
  Secure_allocator(const Secure_allocator &secure_allocator) noexcept
```

7.
```
/data/percona-xtrabackup/8.0/storage/innobase/xtrabackup/src/xbcloud/xbcloud.cc:1157:15: error: lambda capture 'cntx' is not used [-Werror,-Wunused-lambda-capture]
            [&cntx, &thread_state](bool success, const Http_buffer &contents,
```

8.
```
/data/percona-xtrabackup/8.0/storage/innobase/xtrabackup/src/rapidxml/rapidxml.hpp:85:42: error: dynamic exception specifications are deprecated [-Werror,-Wdeprecated-dynamic-exception-spec]
        virtual const char *what() const throw() override
```