Bug#28255462 SEPARATE THE UDF CODE FOR DIFFERENT TYPES OF FUNCTIONS
Post-push fix, warning from clang/Mac
plugin/group_replication/src/udf/udf_registration.cc:36:5: error:
suggest braces around initialization of
      subobject [-Werror,-Wmissing-braces]

Change-Id: I72e65fcc32a7c3ac5095591fbbaff9c8a49ede23
(cherry picked from commit 107818aa6d78c470d946ceb6d71704fc10577bda)