Bug #32433090 RUN CLANG-TIDY MODERNIZE-USE-EQUALS-DEFAULT OVER THE CODE BASE
Use run-clang-tidy.py -fix -checks='-*,modernize-use-equals-default'

This check replaces default bodies of special member functions with = default;

The explicitly defaulted function declarations enable more
opportunities in optimization, because the compiler might treat
explicitly defaulted functions as trivial.

Performance changes, as measured by sysbench with default argumens,
are in the noise area. A small improvement for PGO/LTO builds.

With gcc10, mysqld is about 14 MB smaller with ' = default;'
constructors and destructors.

A few manual fixes were applied to the clang-tidy result:

Fixes for -Werror=unused-parameter
-cs::apply::Commit_order_queue::Iterator::Iterator(const Iterator &rhs)
+cs::apply::Commit_order_queue::Iterator::Iterator(const Iterator &)

-cs::apply::Commit_order_queue::Iterator::operator=(const Iterator &rhs) = default;
+cs::apply::Commit_order_queue::Iterator::operator=(const Iterator &) = default;

Revert some of the changes done by clang-tidy, such as

error: use of deleted function
SortingIterator::IteratorHolder::~IteratorHolder()

router/src/harness/include/mysql/harness/stdx/expected.h:111:3: note:
stdx::base::storage_t<T, E>::storage_t()
[with T = const char*; E = std::error_code]
is implicitly deleted because the default definition would be ill-formed:
  111 |   storage_t() = default;

The reverted changes have been tagged with
// NOLINT(modernize-use-equals-default)
or
// NOLINTNEXTLINE(modernize-use-equals-default)
to prevent clang-tidy to try to fix them later.

The DTOR Item::~Item() was rewritten manually.
The body contained an ifdef, so clang-tidy would not rewrite it.

Other CTORs/DTORs could also be rewritten, e.g. Rsegs() and ~Rsegs() in InnoDB.

Change-Id: I0457e799464119d1f4042589f404dd4b172440e8