Bug#34031693: Data are not repartitioned when the partition key's charset is modified
Post-push fix:

sql/sql_table.cc:4311:49: error:
unused parameter 'field' [-Werror=unused-parameter]

Change-Id: I8750e994ddc0547e7c585ed83d58fe71bfac7739