BUG#31173103 UNHEX() string function performance improvement
Post-push fix for broken build on windows:
\mysys\unhex.cc(87,14): error C2039:  'ptrdiff_t': is not a member of 'std'

Change-Id: Ib6863556e83678b0bbc437097160fd54d2e6235e
(cherry picked from commit 30d3a099356aacdd3ce5348e3bf78ce9be539431)