Bug#34853213 Angel data node does not detect if child data node exits normally
Post push fix for compiler warning from clang.

  storage/ndb/src/kernel/angel.cpp:126:10: error: braces around scalar
initializer [-Werror,-Wbraced-scalar-init]
  return {h};
         ^~~

The intention with braces is to get a warning whenever a narrowing
conversion occurs (pid_t -> std::int_max_64t). Such narrowing is not
known to happen and thus the braces are removed in order to silence the
warning.

Change-Id: I39c3e6d5187747dd55824bab5ba9fd126bad2dd5