Bug#34091087:Timeout on setting group_replication_force_members throws SQLSyntaxErrorExceptio
Issue:
======
When there is a timeout in the view change after setting the
group_replication_force_members variable through below command:

> SET GLOBAL group_replication_force_members=value;

only below error is logged in mysql error log:

[ERROR] [MY-011723] [Repl] Plugin group_replication reported: 'Timeout on
wait for view after setting group_replication_force_members value 'IP:PORT'
into group communication interfaces'

And there is no error message is returned and error number returned are
also incorrect.

The Java client receives a misleading error saying,
Error: 'Failed to force new group membership:
java.sql.SQLSyntaxErrorException: Variable 'group_replication_force_members'
can't be set to the value of 'IP:PORT' [statement:"SET GLOBAL
group_replication_force_members=:value", arguments:{positional:{},
named:{value:IP:PORT}, finder:[]}]'

Solution:
=========
Return correct error and error message when group_replication_force_members
is being set.

Change-Id: I9b7f4848e1d37984083b672d9150a5da16962be4