PXB-2690 - MySQL 8.0.28 merge - fix unused variable
/work/pxb/src/8.0/libbinlogevents/src/gtids/gtidset.cpp: In member function ‘virtual std::size_t binary_log::gtids::Gtid_set::count() const’:
/work/pxb/src/8.0/libbinlogevents/src/gtids/gtidset.cpp:238:36: error: unused variable ‘uuid’ [-Werror=unused-variable]
   for (auto const &[uuid, intervals] : m_gtid_set) {
                                    ^

gtidset.cpp was iterating over a map using only the second position
causing the variable storing the first position to issue an error.