Bug #32433090 RUN CLANG-TIDY MODERNIZE-USE-EQUALS-DEFAULT OVER THE CODE BASE
Post-push fix for Sun Studio:

The data dictionary code has some virtual multiple inheritance in its
class hierarchy.  The base classes of the hierarchy need to have
explicit empty destructors, the compiler fails to generate proper
default DTORs.

The audit log plugin has several interface classes, with no state, and
only pure virtual functions. For *some* of these classes, Sun Studio
fails to generate a default destructors, so we must explicitly define
empty destructors instead.

There's a unit test which segfaults for any optimization level above -xO0.

Some unit tests with mock classes deriving (indirectly) from class Field
need an explicit empty DTOR, otherwise googlemock reports
ERROR: this mock object .... should be deleted but never is.

Change-Id: I8c4b0f17d5eb02a4bd0bc19ae37758a417fcb1a3