Bug#33630320 extra-semi warnings when building metadata_cache_export_all
Issue
=====

Building router with -DWITH_PROTOBUF=system and protobuf 3.12.4 leads
to:

  plugin/x/generated/protobuf_lite/mysqlx.pb.h:173:55: error: extra ‘;’
  after in-class function definition [-Werror=extra-semi]
    173 |   inline ClientMessages() : ClientMessages(nullptr) {};

when it builds the metadata_cache_export_all (static-lib) target.

It does not generate the warning when building the same sources into the
metadata_cache (shared-lib) target.

The main different between the two targets is how the include-path for
"mysqlx.pb.h" is set:

metadata_cache: -isystem plugin/x/generated/protobuf_lite/
metadata_cache_export_all: -Iplugin/x/generated/protobuf_lite/

The extra-semi-warning is disabled for system-includes.

Change
======

- set TARGET_INCLUDE_DIRECTORIES() on mysqlxmessages and mysqlxclient
- removed all manual include-dirs referencing 'plugin/x/client' and
  '${MYSQLX_GENERATE_DIR}'

RB: 27430