Bug#31888723: TEST INNODB.DBLWR_DISABLE FAILS SPORADICALLY IN PB2 MYSQL-TRUNK
Post-push fix for broken build on ARM.

storage/innobase/ut/ut0test.cc:213:76: error: requested alignment 512 is larger than 16 [-Werror=attributes]
  213 |   alignas(OS_FILE_LOG_BLOCK_SIZE) std::array<byte, OS_FILE_LOG_BLOCK_SIZE> buf;

The affected code is test/debug only, and it does work OK.
So we downgrade the -Werror to warning to unbreak the build.

Change-Id: I64c0c6586988071bc05030ee66381aba9da0b488