BUG#27087931: CLANG THROWS SQL_SERVICE_INTERFACE.CC:26 ERROR: UNUSED VARIABLE 'COMMAND_NAME'
The fix for BUG#26787288: CHECK_WARNINGS FOR
GROUP_REPLICATION.GR_RELAY_LOG_NAME_CHANGE TIMES OUT ON PB2 removed the
use of the command_name array.

Removed the command_name due to cause failures with clang compiler.