Bug#30188010 wrong error message if process-launcher fails on win32
Problem
=======

In case the ProcessLauncher fails on on windows it tries to
generate an error-msg that may look like:

    SystemError: The handle is invalid. with error code %d6.:
    no such device or address

in case of ERROR_INVALID_HANDLE.

Analysis
========

ProcessLauchner::report_error() generates an error-msg and throws
it as std::system_error(). The error-msg

1. contains a "%d" which shouldn't appear
2. reports the reason in two places
3. reports the wrong reason in the 2nd case

report_error() duplicates the work that std::system_error() already
does and is a left-over from days where std::runtime_error() was
used by report_error().

Change
======

- replaced ::report_error() by throwing std::system_error()
  directly
- fixed the error-category of error-code that's used on windows
- removed ProcessLauchner::report_error()

RB: 22838