Bug#32876974 ADD HARDENING FLAGS TO STANDALONE BUILDS ON DEB/RPM PLATFORMS.
Additional patch to fix compilation warning/failure in ndb_cpcd, this is
an internal NDB tool which has a "show version" command returning the
time and date of compile.

storage/ndb/src/cw/cpcd/APIService.cpp:403:44: error: macro "__DATE__"
might prevent reproducible builds [-Werror=date-time]
  403 |   m_output->println("compile time: %s %s", __DATE__, __TIME__);
      |                                            ^~~~~~~~

Fix by removing the compile time+date from "show version" in ndb_cpcd
since it's not used by cpcd client.

Change-Id: I6917ce31759b9706d546087c0835b5257bfe78ab
(cherry picked from commit b2c02533af4e162333948d3a65e981247ff272e9)