Revert "Bug #24527148: SERVER CRASH WITH COMPONENT LOAD/UNLOAD CONCURRENTLY"
Does not compile:
In file included from /home/ogrovlen/mysql-git/mysql-trunk/unittest/gunit/components/mysql_server/registry-t.cc:24:0:
/home/ogrovlen/mysql-git/mysql-trunk/components/mysql_server/persistent_dynamic_loader.h:140:10: error: ‘mysql_mutex_t’ does not name a type
   static mysql_mutex_t component_id_by_urn_mutex;

This reverts commit 466f48522ebdd82847472ab8f6b49628d1222650.