8.0.29 merge - compilation fixes
In file included from /work/boost/boost_1_77_0/boost/container/string.hpp:51,
from /work/pxb/src/8.0/components/keyrings/common/data/global_default_mr.h:15,
from /work/pxb/src/8.0/components/keyrings/common/data/data.h:28,
from /work/pxb/src/8.0/components/keyrings/common/operations/operations.h:28,
from /work/pxb/src/8.0/components/keyrings/keyring_file/keyring_file.h:29,
from /work/pxb/src/8.0/components/keyrings/keyring_file/service_implementation/keyring_encryption_service_definition.cc:23:
/work/boost/boost_1_77_0/boost/intrusive/detail/hash_combine.hpp:68:31: error: "ULONG_MAX" is not defined, evaluates to 0 [-Werror=undef]
68 | !(defined(__GNUC__) && ULONG_MAX == 0xffffffff)

Added climits before invoking boost - KMIP

In file included from /work/boost/boost_1_77_0/boost/container/new_allocator.hpp:24,
from /work/boost/boost_1_77_0/boost/container/pmr/polymorphic_allocator.hpp:22,
from /work/pxb/src/8.0/components/keyrings/common/data/global_default_mr.h:14,
from /work/pxb/src/8.0/components/keyrings/common/data/data.h:28,
from /work/pxb/src/8.0/components/keyrings/common/json_data/json_writer.h:35,
from /work/pxb/src/8.0/components/keyrings/keyring_file/backend/backend.h:28,
from /work/pxb/src/8.0/components/keyrings/keyring_file/backend/backend.cc:26:
/work/pxb/src/8.0/include/boost_1_77_0/patches/boost/container/throw_exception.hpp:62:31: error: expected ‘;’ at end of member declaration
62 | virtual const char *what() override const BOOST_NOEXCEPT_OR_NOTHROW
| ^~~~~~~~
|

Added boost patch

/work/pxb/src/8.0/sql/mysqld.cc: In constructor ‘Plugin_and_data_dir_option_parser::Plugin_and_data_dir_option_parser(int, char**)’:
/work/pxb/src/8.0/sql/mysqld.cc:6976:31: error: too few arguments to function ‘int my_handle_options(int*, char***, const my_option*, my_get_one_option, const char**, bool, bool)’
6976 | true)) {
| ^
In file included from /work/pxb/src/8.0/sql/mysqld.h:42,
from /work/pxb/src/8.0/sql/mysqld.cc:689:
/work/pxb/src/8.0/include/my_getopt.h:150:12: note: declared here
150 | extern int my_handle_options(int *argc, char ***argv,
| ^~~~~~~~~~~~~~~~~

PXB has it's own parameters - 110a166f added a new call to my_handle_options that needed fix

/work/pxb/src/8.0/storage/innobase/dict/dict0dd.cc: In function ‘dict_table_t* dd_table_create_on_dd_obj(const dd::Table*, const dd::Partition*, const String_type*, bool, space_id_t)’:
/work/pxb/src/8.0/storage/innobase/dict/dict0dd.cc:445:42: error: too few arguments to function ‘mem_heap_t* mem_heap_create(ulint, ut::Location)’
445 | mem_heap_t *heap = mem_heap_create(1000);
| ^

e001f2 Added a new parameter to mem_heap_create to set its location.

/work/pxb/src/8.0/storage/innobase/dict/dict0dd.cc: In function ‘dict_table_t* dd_table_create_on_dd_obj(const dd::Table*, const dd::Partition*, const String_type*, bool, space_id_t)’:
/work/pxb/src/8.0/storage/innobase/dict/dict0dd.cc:841:5: error: ‘dd_fill_instant_columns_default’ was not declared in this scope; did you mean ‘dd_fill_instant_columns’?
841 | dd_fill_instant_columns_default(*dd_table, table);
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

e8f422d - Renamed dd_fill_instant_columns to dd_fill_instant_columns_default. PXB has this as non static and required to rename it on header file.

/work/pxb/src/8.0/storage/innobase/dict/dict0dd.cc: In function ‘dict_table_t* dd_table_create_on_dd_obj(const dd::Table*, const dd::Partition*, const String_type*, bool, space_id_t)’:
/work/pxb/src/8.0/storage/innobase/dict/dict0dd.cc:859:74: error: ‘FALSE’ was not declared in this scope
859 | dberr_t new_err = dict_index_add_to_cache(table, index, index->page, FALSE);
| ^~~~~

e001f2 - removed the definition of FALSE - we should use false instead.

/work/pxb/src/8.0/storage/innobase/dict/dict0dd.cc: At global scope:
/work/pxb/src/8.0/storage/innobase/dict/dict0dd.cc:4095:13: error: redefinition of ‘bool dd_table_contains_fulltext(const dd::Table&)’
4095 | inline bool dd_table_contains_fulltext(const dd::Table &table) {
| ^~~~~~~~~~~~~~~~~~~~~~~~~~

PXB code uses this function earlier than its definition. As part of 1d23392 it re-introduced it.

/work/pxb/src/8.0/storage/innobase/dict/dict0dd.cc: In function ‘dict_table_t* dd_table_create_on_dd_obj(const dd::Table*, const dd::Partition*, const String_type*, bool, space_id_t)’:
/work/pxb/src/8.0/storage/innobase/dict/dict0dd.cc:956:53: error: too few arguments to function ‘void rw_lock_x_lock(rw_lock_t*, ut::Location)’
956 | rw_lock_x_lock(&table->fts->cache->init_lock);

e001f2 Added a new parameter to rw_lock_x_lock to set its location.

/work/pxb/src/8.0/storage/innobase/dict/dict0dd.cc:1127:45: error: too many arguments to function ‘void dict_table_add_to_cache(dict_table_t*, bool)’
1127 | dict_table_add_to_cache(table, false, heap);
| ^

3e5b3b24a6b2 removed heap as parameter

/work/pxb/src/8.0/storage/innobase/dict/dict0dd.cc: In function ‘void dd_process_schema_rec(mem_heap_t*, const rec_t*, dict_table_t*, mtr_t*, std::string*, uint64*)’:
/work/pxb/src/8.0/storage/innobase/dict/dict0dd.cc:6257:43: error: cannot convert ‘const rec_t*’ {aka ‘const unsigned char*’} to ‘const dict_index_t*’
6257 | field = (const byte *)rec_get_nth_field(rec, offsets,
| ^~~
| |
| const rec_t* {aka const unsigned char*}

e8f422d - instant drop collum added a new field to rec_get_nth_field, we should call it as nullptr

/work/pxb/src/8.0/storage/innobase/xtrabackup/src/space_map.cc: In member function ‘bool Tablespace_map::serialize(ds_ctxt_t*) const’:
/work/pxb/src/8.0/storage/innobase/xtrabackup/src/space_map.cc:209:30: error: ‘time_t my_time(int)’ is deprecated [-Werror=deprecated-declarations]
209 | mystat.st_mtime = my_time(0);
| ^

7230b2e deprecated my_time

/work/pxb/src/8.0/storage/innobase/xtrabackup/src/redo_log.cc: In member function ‘ssize_t Archived_Redo_Log_Reader::read_logfile(bool*)’:
/work/pxb/src/8.0/storage/innobase/xtrabackup/src/redo_log.cc:527:57: error: no matching function for call to ‘Encryption::decrypt_log(IORequest&, ut::aligned_array_pointer<unsigned char, 65536>&, long unsigned int&, ut::aligned_array_pointer<unsigned char, 65536>&, const size_t&)’
527 | UNIV_PAGE_SIZE_MAX);
| ^

85f9abf99075 removed one unused parameter from decrypt_log

/work/pxb/src/8.0/storage/innobase/include/os0enc.h:386:11: note: candidate expects 4 arguments, 5 provided
/work/pxb/src/8.0/storage/innobase/xtrabackup/src/redo_log.cc: In member function ‘bool Redo_Log_Data_Manager::init()’:
/work/pxb/src/8.0/storage/innobase/xtrabackup/src/redo_log.cc:947:41: error: too many arguments to function ‘void recv_sys_init()’
947 | recv_sys_init(buf_pool_get_curr_size());
| ^
85f9abf99075 removed one unused parameter from recv_sys_init

/work/pxb/src/8.0/storage/innobase/xtrabackup/src/xtrabackup.cc: In function ‘bool xb_space_create_file(const char*, ulint, ulint, fil_space_t*, pfs_os_file_t*)’:
/work/pxb/src/8.0/storage/innobase/xtrabackup/src/xtrabackup.cc:5287:57: error: too many arguments to function ‘bool os_file_set_size(const char*, pfs_os_file_t, os_offset_t, os_offset_t, bool)’
5287 | srv_read_only_mode, false);
| ^
In file included from /work/pxb/src/8.0/storage/innobase/include/log0types.h:53,
from /work/pxb/src/8.0/storage/innobase/include/mach0data.ic:36,
from /work/pxb/src/8.0/storage/innobase/include/mach0data.h:287,
from /work/pxb/src/8.0/storage/innobase/include/data0type.ic:34,
from /work/pxb/src/8.0/storage/innobase/include/data0type.h:540,
from /work/pxb/src/8.0/storage/innobase/include/rem0types.h:36,
from /work/pxb/src/8.0/storage/innobase/include/dict0types.h:39,
from /work/pxb/src/8.0/storage/innobase/include/row0quiesce.h:37,
from /work/pxb/src/8.0/storage/innobase/xtrabackup/src/xtrabackup.cc:49:
/work/pxb/src/8.0/storage/innobase/include/os0file.h:1480:20: note: declared here
1480 | [[nodiscard]] bool os_file_set_size(const char *name, pfs_os_file_t file,
| ^~~~~~~~~~~~~~~~

c7d556c removed read_only argument from os_file_set_size

/work/pxb/src/8.0/storage/innobase/xtrabackup/src/xtrabackup.cc: In function ‘bool innodb_init_param()’:
/work/pxb/src/8.0/storage/innobase/xtrabackup/src/xtrabackup.cc:1893:3: error: ‘get_charset_name’ was not declared in this scope; did you mean ‘get_charset_by_name’?
1893 | get_charset_name(0);
| ^~~~~~~~~~~~~~~~
| get_charset_by_name

d55e3b9 renamed 
the function get_charset_name() to get_collation_name().

In file included from /work/pxb/src/8.0/storage/innobase/xtrabackup/src/xtrabackup.cc:1252:
/work/pxb/src/8.0/include/sslopt-longopts.h:207:6: error: ‘OPT_SSL_SESSION_DATA’ was not declared in this scope; did you mean ‘MYSQL_OPT_SSL_SESSION_DATA’?
207 | OPT_SSL_SESSION_DATA,
| ^~~~~~~~~~~~~~~~~~~~
| MYSQL_OPT_SSL_SESSION_DATA
/work/pxb/src/8.0/include/sslopt-longopts.h:221:6: error: ‘OPT_SSL_SESSION_DATA_CONTINUE_ON_FAILED_REUSE’ was not declared in this scope
221 | OPT_SSL_SESSION_DATA_CONTINUE_ON_FAILED_REUSE,
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /work/pxb/src/8.0/storage/innobase/xtrabackup/src/xtrabackup.cc:1848:
/work/pxb/src/8.0/include/sslopt-case.h: In function ‘bool xb_get_one_option(int, const my_option*, char*)’:
/work/pxb/src/8.0/include/sslopt-case.h:51:6: error: ‘OPT_SSL_SESSION_DATA’ was not declared in this scope; did you mean ‘MYSQL_OPT_SSL_SESSION_DATA’?
51 | case OPT_SSL_SESSION_DATA:
| ^~~~~~~~~~~~~~~~~~~~
| MYSQL_OPT_SSL_SESSION_DATA

bee2a1f added new SSL options, need to add them to pxb too

/work/pxb/src/8.0/sql/join_optimizer/join_optimizer.cc: In member function ‘size_t {anonymous}::CostingReceiver::num_access_paths() const’:
/work/pxb/src/8.0/sql/join_optimizer/join_optimizer.cc:233:37: error: unused variable ‘nodes’ [-Werror=unused-variable]
     for (const auto &[nodes, pathset] : m_access_paths) {
                                     ^
[ 75%] Building CXX object sql/CMakeFiles/sql_main.dir/opt_hints.cc.o
/work/pxb/src/8.0/sql/join_optimizer/join_optimizer.cc: In member function ‘void {anonymous}::CostingReceiver::ProposeNestedLoopJoin(hypergraph::NodeMap, hypergraph::NodeMap, AccessPath*, AccessPath*, const JoinPredicate*, bool, FunctionalDependencySet, OrderingSet)’:
/work/pxb/src/8.0/sql/join_optimizer/join_optimizer.cc:3452:56: error: unused variable ‘already_applied_as_sargable’ [-Werror=unused-variable]
       const auto [already_applied_as_sargable, subsumed] =
                                                        ^
/work/pxb/src/8.0/sql/join_optimizer/join_optimizer.cc: In member function ‘double {anonymous}::CostingReceiver::FindAlreadyAppliedSelectivity(const JoinPredicate*, const AccessPath*, const AccessPath*, hypergraph::NodeMap, hypergraph::NodeMap)’:
/work/pxb/src/8.0/sql/join_optimizer/join_optimizer.cc:3568:54: error: unused variable ‘subsumed’ [-Werror=unused-variable]
     const auto [already_applied_as_sargable, subsumed] =
                                                      ^

added pragmas to silent unused variable warning.