Bug#34869076 use-after-free if mysql_bind_param() fails - postfix
Fixed build fail with msvc:

testclients\mysql_client_test.cc(23475,11): error C7555: use of
designated initializers requires at least '/std:c++20'

Change
------

- replaced designated initializers with direct assignment

Change-Id: I78c40d512aab83cafab14d7aa18f16fef7aa501f