BUG#28252687 - WHEN A MEMBER GOES TO ERROR, OTHER MEMBERS SEE IT UNREACHABLE
Post-push fix:
cs_xcom_control_interface.cc:674:13: error:
      unused variable 'port' [-Werror,-Wunused-variable]

Change-Id: I8f0a47358b358ecf92637dd28611049fc131585a