Bug#26188578 Bug#26164633 Bug#26360114 Bug#26781725 Bug#26848089 Regressions with WL#9236
Bug#26188578 WL#9603: HAVING CONDITION IS OPTIMIZED OUT FOR ALIAS ON AGGREGATE W/O GROUP BY
Bug#26164633 WL#9603: WRONG RESULT WHEN PARTITION EXPR USING AGGREGATES EVALUATES TO NULL
Bug#26360114 WRONG RESULT WITH AGGREGATE AND HAVING CLAUSE IN VIEW
Bug#26781725 INCORRECT RESULTS FOR QUERY(MAX FUNC+HAVING CLAUSE) WHEN USED INSIDE VIEW
Bug#26848089 LEAD/LAG WINDOW FUNCTIONS ON QUOTED JSON STRINGS RETURNS SAME VALUE FOR ALL ROWS

Regressions introduced by changes to Item_ref done in the patch for
window functions (WL#9236).

Background of existing design before the WL of window functions:

- Item_ref is very old design which was introduced for SQL clause
HAVING, when HAVING references an item of the SELECT list through an
alias. It points to an Item ('ref' pointer). When there is a tmp table
involved in the execution (e.g. GROUP BY before HAVING), we may
calculate a SELECT list expression (let's say it's an Item_func) and
store it in the tmp table in the group's row. The
tmp table's column where it's stored is known as the Item's result_field.
If HAVING references that expression through an alias, HAVING contains
Item_ref with a 'ref' pointing to the Item_func. When evaluating
HAVING, we want to use the already calculated value of Item_func
(_not_ evaluating the Item_func again, as it may not be deterministic),
we do that by looking at the value stored in ref->result_field.
That is why Item_ref::val_int calls ref->val_int_result(), not
val_int().
- So the system is relying on the capacity of Item_ref to
automatically pick the stored value.
- While that sounds ok for queries with no or only one tmp table, it
is not enough for more complex queries
- hence, a second design: "ref item slices": in different phases of
execution (simply: depending on which table, tmp or non-tmp,
we're reading now), a same SELECTed expression is represented by
different Items: it may be SUM initially (Item_sum), then, once
calculated (with Item_sum::val_int()) and stored in a tmp table with
one row per group, it becomes Item_field (a column of the tmp
table). After all groups have been written, if a filesort is used
to do a final ORDER BY, that sort must call the Item_field's val_int,
not the Item_sum::val_int which is just the value of the last group.
- So, depending on which table we're reading now, the SELECTed
expression is one object or another; for that, we wrap the expression
in Item_ref, with 'ref' pointing to a place (a cell in the "ref item
slice"), and at this place we deposit a pointer either to the original
Item_sum or to the tmp table's Item_field, depending on the phase
we're in.
Phases are identified by numbers (grep for the REF_SLICE enum).

With the advent of window functions, more tmp tables are used, and
form a chain. The fact that Item_ref::val_int always reads ref->result_field
(i.e. what was saved in the next tmp table) sometimes leads to reading
not-yet-calculated data from the next tmp table.
For example, if we have an Item_func I_F, and a tmp table used for windowing,
and we have an Item_ref I_R to the I_F (HAVING always creates an
Item_ref), and before the tmp table is written we use I_R::val_int,
that gets the value of I_F->result_field, reading random data from the
tmp table. Such I_R::val_int() (or val_int_result(), equivalently)
could occur in filesort(), for example.
HAVING is one problem; but the ORDER BY clauses of windowing also use
Item_ref; and aggregate functions also do (if involved in a more
complex expression, see Item::split_sum_func2). Aggregate functions
may be used as arguments to windows, so, depending on the phase,
Item_ref should pick the aggregate function's value or its saved
value, which it can't do. The behaviour of Item_ref of "always reading
the result_field", combined with the increased number of tmp tables,
made things harder to manage than they used to be.

So things are refactored in this patch:
- Item_ref::val_(int,etc)() just calls ref->val_(int,etc)(), doesn't
read ref->result_field anymore
- when you are reading QEP_TAB Q and want to evaluate an expression
which depends on values stored in Q and previous tables in the
execution order, switch to Q->ref_item_slice slice: it will switch to
Items which point into Q's table.
- when you are doing a GROUP BY where grouped rows are not
materialized in a tmp table (because rows are produced in group order
by the join), a pseudo-tmp table buffer is used (no change here); if
you want to evaluate an expression which depends on values
stored in this buffer, use the REF_SLICE_TMP3 slice.
- the reads above include: sorting the table, evaluating a condition
on the table, etc.

Changes:

All val_*result() are removed.
So Item_ref::val_(int,etc) calls ref->val_(int,etc), not
val_result. Thus, "ref" needs to be "advanced by one step", as we
don't look into "its result already stored into the next tmp
table", anymore. So ref slices are "advanced by one  step" during
execution.
Unchanged meaning of "the current ref slice of JOIN":
it's still the "ref"s (targets) for Item_refs when evaluating Items in
the current phase of execution.
Unchanged meaning of QEP_TAB::ref_item_slice: the
it's still the "ref"s (targets) for Item_refs when evaluating Items
when reading this QEP_TAB.
Exception: QEP_TAB::ref_item_slice is not anymore set to
REF_SLICE_TMP3, as that latter slice is never the one to use to read
from any QEP_TAB; it's the one to use to read from a pseudo-tmp-table
of GROUP BY. A consequence is that we cannot use
QEP_TAB::ref_item_slice to switch to REF_SLICE_TMP3 anymore, so we use
a new member JOIN::before_ref_item_slice_tmp3 for that.
Almost all execution functions need to advance to the right slice
before they read a table.

QEP_TAB::all_fields and QEP_TAB::fields are removed: we can get the
same information from QEP_TAB::ref_item_slice, using new function
JOIN::get_current_fields().

class Item:
all val_x_result() are gone, all calls to them replaced with val_x().
Item_ref made to behave like Item_direct_ref; thus, Item_direct_ref
removed and replaced with Item_ref.

Item_field::save_in_field_inner() (item.cc):
    after the changes done to fix_inner_refs() in this patch,
    for the materialization of some IN subquery, we use store_key_item
    to store the left args of the IN subquery,
    while we used to use store_key_field (see comment about fix_inner_refs);
    these left args are indeed outer refs belonging to a grouped query;
    store_key_field() takes its source in Item_field::field;
    store_key_item() rather uses Item_field::save_in_field_inner()
    which takes its source in Item_field::result_field, which assumes
    this field contains the up-to-date value. This logic sounds
    strange and the present patch uses the "field" member as source,
    instead. Perhaps the old logic was necessary when ref slice wasn't
    "advanced one step" as we do now. The modified code is from before
    2000 so we cannot know more about its reason.

item_subselect.cc: ref_by[1] introduced (see explanation there). So we
now have two "ref_by" pointers; it's then difficult to pass both as
arguments to split_sum_func2 in sql_resolver.cc so we let
split_sum_func2 find pointers itself.

sql_join_buffer.cc: assert that we needn't switch slice, because we never
use join buffer on a tmp table. Removed useless switch.

JOIN::set_ref_item_slice(): as we use it more now, make it do nothing if
slice number doesn't change (optimization).
Switch_ref_item_slice: now it's used in one case where the said slice
may or not exist, so I make the object a no-op if the slice doesn't
exist.

JOIN::set_group_rpa: not needed anymore as set_ref_item_slice()
detects when sliceno doesn't change so we can call it repeatedly;
removed.

SELECT_LEX::fix_inner_refs(): simplified as Item_direct_ref and
Item_ref are one now, no need to choose between the two.

sql_select.cc:get_store_key():
there was an "else if" branch special for DIRECT_REF.
      else if ((*(Item_ref**)(item_ref)->ref)->ref_type()
               == Item_ref::DIRECT_REF &&
               item_ref->real_item()->type() == Item::FIELD_ITEM)
               field_item= static_cast<Item_field*>(item_ref->real_item());
It was specific of an outer reference belonging to a query with GROUP
BY. It relied on the two different types of Items created in
fix_inner_refs(). I remove this because it's not possible anymore to
distinguish Item_ref from Item_direct_ref (they're one now), and the
distinction is necessary to make this 'else' work. Likely it makes us
pick store_key_item() instead of store_key_field(), in this outer-ref
case, which is acceptable.

sql_select.cc: reset_wf_result_fields(): removed.
  More info about the problem that required this function:
  select from (select WF1 over w1, WF2 over w2) dt;
  where "dt" is materialized. First the "dt" table structure is created with
  create_tmp_table() and that sets WF{1,2}->result_field (pointing into
  columns of "dt"). Then the inner subquery is optimized, that calls
  create_tmp_table() for the two windows. First for w1: WF1 is to be
  calculated in w1 so a column is added for its result in the tmp table; so
  its result_field gets re-set to point there, all fine. Continuing with the
  creation of wf1, WF2 is skipped. Then change_to_use_tmp_fields() sees that
  WF1 and WF2 have a result_field (see test
  'else if ((field= item->get_tmp_table_field()))'), so concludes that the ref
  slice used to read the tmp table of w1 should contain Item_fields for WF1
  and WF2; that's incorrect for WF2, and leads to WF2 never being calculated.
  My fix: in create_tmp_table(), when the destination table is to materialize
  a derived table / UNION (i.e. is not a group-by/windowing table), there's no
  reason to set result_field (results are not saved by this means anyway, but
  by Query_result_union::send_data() which reads the last table of the query
  and writes that to the materialized table), so don't set it.

sql_select.cc: JOIN::make_tmp_tables_info():
      Complement to comment "Exit the TMP3 slice": failing test was
      main.func_group, consider:
      SELECT (SELECT COUNT(DISTINCT t1.b)) FROM t1 GROUP BY t1.a;
      When evaluating COUNT(DISTINCT t1.b): we copy t1.b to tmp table used by
      COUNT(DISTINCT) (i.e. tmp table of Aggregator_distinct):
      for that we must copy t1.b from JOIN's result, not from TMP3 slice:
      indeed TMP3 was filled when we switched to a new group (see
      end_send_group), so it contains the value of t1.b for the first row of
      the group; while COUNT(DISTINCT) wants the value of the current row (or
      it would think all rows of group have same value of t1.b). So the
      copy_field to the COUNT(DISTINCT) tmp table must take its source in
      JOIN, so ref slice must not be TMP3 in setup_sum_funcs.
      Alternatively, I tried to let COUNT(DISTINCT) read from TMP3, so I had
      to update t1.b in TMP3 for every read row but:
      - it broke the undocumented behaviour that "for a non-functionally dependent
      column in group we choose first row"
      - it broke other tests

sql_executor.cc:
simplified slice switching: switch, when about to read a table, to the
Items which point to this table; in practice it means:
- before reading first row (as it may start with a filesort, which may
have to evaluate some ORDER BY expression on the table); slice switch
remains in force for next rows too
- for tmp tables: before evaluating HAVING; even a bit earlier: before
copy_fields() (see comment in end_send_group())
- copy_funcs(): no need to calculate functions in two passes, anymore;
so tmp_table_param::hidden_func_count is removed (was added by the WF
WL). Proper order is given by sort_copy_func() now.
- setup_copy_fields(): no need for special case for Item_aggregate_ref,
said Evgeny; indeed I don't understand why it still would be needed:
as Item_ref::val_* just evaluates the referenced Item_field (doesn't
look at result_field), we can just copy the underlying Item_field.
- complement to comment "As GROUP expressions have changed" at *end* of
end_send_group():
        Fixes test: main.group_by, query:
        select a, round(rand(100)*10) r2, sum(1) r1 from t1 where a = 1 group  by a
        having r1>1 and r2<=2;
- complement to comment "We have created a new Item_field" in
setup_copy_fields():
            The only new thing is below: let 'item->field' allow access to
            REF_SLICE_TMP3. This won't disturb the Copy_field as it has cached
            field->ptr (in copy_field->set()) before the change to
            'item->field' below.
            Why this change: because when we are in slice TMP3 (end_send_group), to
            evaluate HAVING we use Item_ref::val_int() which doesn't anymore use
            ref->val_int_result() but ref->val_int() instead: and
            Item_field::val_int() uses 'field' not 'result_field' so the
            Item_field here must have valid data (i.e. TMP3) in its 'field'.
- change in QEP_TAB::remove_duplicates(): the function
used (this-1)->fields. Now that I get rid rid of this member, I found
a way to do without it: it was used to count hidden fields in 'this';
I replaced the counting with the existing hidden_field_count.
- assertions of type:
  this != join()->before_ref_item_slice_tmp3
are added to make sure that only well-identified functions read from
REF_SLICE_TMP3.

sql_tmp_table.cc:
- don't set result_field when it doesn't make sense;
removes the need to clear it later (i.e. removed
reset_wf_result_fields()).
- as we can now create a tmp table by using as source the fields of slice
REF_SLICE_TMP3, which don't point in a real table::record[0], fixed the
"move_field" logic in calculation of the field's default value.
- added sort_copy_func() to evaluate Copy_func-s in proper order (see
comment there); uses new function Item_ref::contains_alias_of_expr()
(item.cc); requires to replace Item* pointer in Func_ptr_array with a
pair of Item* and alias-of-expr property: class Func_ptr.
- complement to comment "Let each group expression know"
      it is needed to fix Bug#26475312. Indeed, the scenario was (see
      test in window_functions_bugs.test):
      - for group-by write to a tmp table tmp1
      - there is no group aggregate function (so this GROUP BY is there only
      to make distinct groups) so we use end_write() with a duplicate
      elimination in tmp1
      - the concatenation of group expressions is too long to make it a unique
      key so we use a "unique constraint" (hash_field) instead
      - after tmp1 there is tmp2 for windowing.
      - in end_write() we do check_unique_constraint(); after checking
      hash_field it gets a "candidate duplicate"; to check it more thoroughly
      we use group_rec_cmp() to compare the two rows; this function finds the
      value of group expressions in each row; for that it evaluates the
      expressions; but (after the refactoring) the slice we're at is that of
      tmp1 (not of the table before tmp1, anymore); the expression is
      thus a Item_field with 'field' in tmp1; and 'result_field' in tmp2; when
      group_rec_cmp() used get_tmp_table_item() on this Item_field it returned
      result_field i.e. group_rec_cmp() was reading in tmp2, wrongly.
      The fix is the make group_rec_cmp() find the proper 'field'. We record
      it below. Note that it was recorded in the old code too, but not if using
      hash_field (see branch "if (group && !using_unique_constraint)").
      - I also changed unique_hash_group like group_rec_cmp as they looked
      similar.
- complement to comment "Get the value from default_values":
        Using move_field_offset(diff) below assumes that orig_field->ptr
        points into record[0], which may not be the case. Example:
        - we are creating a tmp table to materialize the query's result, for a
        PS cursor
        - the last table of the query, i.e. input to the cursor's tmp table,
        is the result of GROUP BY, so here 'fields' is items of
        REF_SLICE_TMP3
        - so orig_field is from REF_SLICE_TMP3, it was created by
        setup_copy_fields() from table->field[x] and its ptr points to a
        temporary memory area.
        Conclusion: so we rather use orig_field->table->field[x] which is
        properly in record[0].  By adding 'diff' to ptr we point that field to
        its default value.
        Fixed mysql_client_test.test (precisely the test for bug 11904 there).

table.h: st_order::field renamed to clearer name field_in_tmp_table.

New MTR test bits for better coverage of modified code.
Tests for the four fixed bugs.

having.test: UPDATEs to the series table are added to make sure a
failing section doesn't make other following sections fail.

Change-Id: I9775573b821886932b48b08c5ae9ece12e249e71