WL#14127 EXPLICIT CAST BETWEEN GEOMETRY TYPES
Post-push fix for Werror builds with some clang versons:
sql/gis/geometries_cs.h:178:3: error: definition of implicit copy constructor for
      'Cartesian_linearring' is deprecated because it has a user-declared destructor [-Werror,-Wdeprecated]
  ~Cartesian_linearring() override = default;

Those declarations for default destructors were introduced as a
workaround for a bug in Sun Studio, and are not needed by other
compilers, so wrap them in an ifdef.

Also fix a warning from Apple clang version 12.0.0 (clang-1200.0.32.28)
unittest/gunit/gis_distance-t.cc:146:8: note: use reference type 'const std::initializer_list<double> &' to prevent copying
  for (const auto linestring : data) {
       ^~~~~~~~~~~~~~~~~~~~~~~

Change-Id: Id368a40967f91a5877ddf05b27d127d3e6838558