Merge 8.1 - Fixed compilation warnings in xtrabackup
/work/pxb/src/8.0/storage/innobase/xtrabackup/src/xbcloud/xbcloud.cc:74:66: error: ‘NullS’ was not declared in this scope
   74 | const char *storage_names[] = {"SWIFT", "S3", "GOOGLE", "AZURE", NullS};
      |                                                                  ^~~~~

nullS moved to nulls.h at b845ba2

/work/pxb/src/8.0/storage/innobase/xtrabackup/src/file_utils.cc: In function ‘const char* get_relative_path(const char*)’:
/work/pxb/src/8.0/storage/innobase/xtrabackup/src/file_utils.cc:179:34: error: ‘is_prefix’ was not declared in this scope; did you mean ‘BIO_f_prefix’?
  179 |   if (test_if_hard_path(path) && is_prefix(path, DEFAULT_MYSQL_HOME) &&
      |                                  ^~~~~~~~~

is_prefix was included via chain include. Now we need to manually include the header where it is defined

/work/pxb/src/8.0/components/keyrings/common/config/config_reader.cc:41:34: error: ‘ER_KEYRING_COMPONENT_NO_CONFIG’ was not declared in this scope; did you mean ‘ER_KEYRING_COMPONENT_EXCEPTION’?
   41 |     LogComponentErr(ERROR_LEVEL, ER_KEYRING_COMPONENT_NO_CONFIG,

During merge 8.1 messages took place of Percona section. Fixed by bringing it back.

/work/pxb/src/8.0/include/sslopt-vars.h:35:21: error: extra tokens at end of #ifdef directive [-Werror]
   35 | #ifdef MYSQL_SERVER && !defined(XTRABACKUP)

Adjusted ifdef to if defined

/work/pxb/src/8.0/storage/innobase/xtrabackup/src/backup_mysql.cc:532:5: error: ‘strmake’ was not declared in this scope
  532 |     strmake(mysql_real_data_home, datadir_var, FN_REFLEN - 1);

added missing header

In file included from /work/pxb/src/8.0/storage/innobase/xtrabackup/src/xtrabackup.cc:505:
/work/pxb/src/8.0/include/sslopt-vars.h: In function ‘int set_client_ssl_options(MYSQL*)’:
/work/pxb/src/8.0/include/sslopt-vars.h:118:54: error: ‘opt_tls_sni_servername’ was not declared in this scope
  118 |   mysql_options(mysql, MYSQL_OPT_TLS_SNI_SERVERNAME, opt_tls_sni_servername);

Added missing variable declaration as non static

/work/pxb/src/8.0/include/sslopt-longopts.h:236:6: error: ‘OPT_TLS_SNI_SERVERNAME’ was not declared in this scope; did you mean ‘MYSQL_OPT_TLS_SNI_SERVERNAME’?
  236 |      OPT_TLS_SNI_SERVERNAME,
      |      ^~~~~~~~~~~~~~~~~~~~~~
      |      MYSQL_OPT_TLS_SNI_SERVERNAME

Declared missing ENUM