Bug#34787953 add missing AF_UNIX support on windows
Post-push fix, broken build with gcc13:
router/src/harness/tests/test_net_ts_local.cc:314:36:
error: redundant move in return statement [-Werror=redundant-move]

Change-Id: Ib1d0f31dc9c91575ab3f91afdaecf86bbc5f252f