Bug#26781567 REMOVE C LEGACY Bug#26612465 BUILDING WITH CMAKE 3.9.0 OR NEWER GIVES DEPRECATION WARNINGS
Post push fix for: Move some InnoDB memcached files from C to C++
Turns out we need some 'extern "C"' in order to load the memcached plugin:

bin-ndb/storage/ndb/memcache/ndb_engine.so:
undefined symbol: _Z11slabs_clsidP14default_enginem
$c++filt _Z11slabs_clsidP14default_enginem
slabs_clsid(default_engine*, unsigned long)

_Z12item_releaseP14default_engineP10_hash_item
item_release(default_engine*, _hash_item*)

_Z30default_engine_create_instancemPFP18server_handle_v1_tvEPP16engine_interface
default_engine_create_instance(unsigned long, server_handle_v1_t* (*)(), engine_interface**)

On Mac:
cmake changes to build dbclient_so

storage/ndb/src/common/portlib/NdbCondition.cpp:175
error: no matching
      function for call to 'clock_gettime'
  clock_gettime(clock_id, abstime);

Tested with:
./mtr --mem --suite=ndb_memcache,ndbcluster