Bug#27335346: SYSBENCH CONNECT TEST SHOWS -14% REGRESSION               FOR ROOT USER WITOUT PASSWORD
Post-push fix for clang warning:

sql/auth/sql_authentication.cc:793:26:
error: suggest braces around initialization of
      subobject [-Werror,-Wmissing-braces]
    uint)PLUGIN_LAST] = {C_STRING_WITH_LEN("caching_sha2_password"),

Change-Id: Ibe10c74ce36f2b204cce5239670f62412289dd1b