BUG#32136993 alloc node retry fail for unresolved
The MySQL NDB Cluster Management Server returns wrong status for
hostname matching when some of the hostnames in configuration does not
resolve and client that tries to allocate a nodeid connects from host
whose hostname resolves to a loopback address with this error:

  Error: Could not alloc node id at <host>:port: Connection with
  id X done from wrong host ip 127.0.0.1, expected
  <unresolvable_host>(lookup failed).

This caused the connecting client to fail the node id allocation.

Fix by:
- rewriting match_hostname() to contain all logic for how the
  requesting client address should match the configured hostnames.
- change match_hostname() to first check if configured hostname can
  be resolved. If resolve fails, return the special "no_resolve" error
  so that client get an error indicating that allocation can be retried.
- add comment describing that a client connecting on the loopback
  address is  matched against the configured hostname by trying to bind.
  If the bind works, it can also be used by the client which is assumed
  to be on the same host.
- removing unnecessary casts, straighten up the logic and improve
  comments.

New error with these changes are:

  Error: Could not alloc node id at <host>:<port>: No configured
  host found of node type <type> for connection from ip 127.0.0.1.
  Some hostnames are currently unresolvable. Can be retried.

Change-Id: I534b3b3471973d01294bf512408f033d23e55dc3