Bug#27675699 - FAILED AUTHENTICATION AT X PLUGIN ALWAYS RETURNS ER_ACCESS_DENIED_ERROR
Post-push fix for missing dependency
plugin/x/tests/driver/processor/commands/mysqlxtest_error_names.cc:41:10: fatal error: 'mysqlclient_ername.h' file not

To reproduce:
rm ./include/mysqlclient_ername.h
make mysqlxtest

Change-Id: I15bb91645ff521cebd52be5bc15d79c2af8055b2