Bug #29999782 MYSQLDUMP WERROR=FORMAT-TRUNCATION
Use a larger buffer for snprintf, to avoid:
client/mysqldump.cc:3891:16: error: %s directive output may be truncated
writing up to 194 bytes into a region of size 169
[-Werror=format-truncation=]

Change-Id: I6026c190aa18f18dcc3d0c317004b66ec3d0b7f1
(cherry picked from commit 38b36e102fc98e287c93485658fa0d0f8c046574)