Revert "Bug #29910973: UNIT-TESTS TRIGGER THE TEMPTABLE ALLOCATOR STATIC_ASSERT"
This reverts commit 36f67f56e36d286d1353d12dbba00de080bd96f7.

Broken build with gcc 8
unittest/gunit/temptable_allocator-t.cc:58:21: error:
conversion from 'long unsigned int' to 'unsigned char' changes value from '17297099942680990260' to '52' [-Werror=overflow]
a[i][j] = 0xF00BA4C0FFEE1234; ^~~~~~~~~~~~~~~~~~

Change-Id: Ib4a3b0a57cd1397fa468e288d232031a583adaab