Fix a compilation warning in non-debug builds.
  .../ut0rbt.cc:103:1: error: function 'rbt_count_black_nodes' is not needed and will not be emitted
  [-Werror,-Wunneeded-internal-declaration]
  rbt_count_black_nodes(
  ^
  1 error generated.

It was introduced in 6664da1.