Bug#27707495 SERVER REQUIRES RECENT GCC TO BUILD THE SERVER, OTHERWISE IT FAILS
Problem
error: undefined reference to 'TLS init function for temptable::tables'

TLS wrappers are supported in gcc 4.8.3 an up, so change compiler
version check.

Change-Id: I92e9fa12cf276c04793533a489105725ebdd6291