Bug#30406328 build fails with gcc-5.x and openssl 1.1.x
Problem
=======

GCC 5.5.0 doesn't support "throw" in constexpr which leads to:

In function ‘constexpr int o11x_version(TlsVersion)’:
router/src/http/src/tls_context.cc:99:57:
error: expression ‘<throw-expression>’ is not a constant-expression
       throw std::invalid_argument("version out of range");
                                                         ^

Change
======

remove 'constexpr' as it isn't needed.

RB: 23157