MySQL 8.0.33 merge Fixed compilation error on xtrabckup.cc
Refractoring done on upstream code removed srv_n_file_io_threads variable
commit 1972123c5d7 Bug#34992157 The AIO::s_log unused since WL#1252

compilation error
xtrabackup.cc:2703:3: error: no matching function for call to 'srv_start_threads'
  srv_start_threads(false);

addd56b38217 Bug #33700835 : Crash during background rollback if INSTANT DDL have
removed bootstrap otption for srv_start_threads