Bug: 1678838: compilation error: format '%s' expects argument of type 'char*'
Using table_name instead of table->name, issue was intriduced by merge from 2.3