Bug#26926291 RPL.RPL_SPEC_VARIABLES FAILS ON PB2 SPORADICALLY
Description
-----------
rpl.rpl_spec_variables is seen to be failing on pb2 sporadically
Error output is:

    rpl.rpl_spec_variables 'mix'             w19 [ fail ]
        Test ended at 2017-09-29 21:39:59

    mysqltest: In included file ./include/sync_slave_sql.inc at line 151:
    included from ./include/sync_slave_sql_with_master.inc at line 79:
    included from ./mysql-commercial-9.0.0-dmr-linux-x86_64-valgrind/mysql-test/suite/rpl/t/
       rpl_spec_variables.test at line 204:
    At line 150: Error in sync_with_master.inc

    ERROR: sync_slave_sql.inc failed on connection 'slave'
    ERROR: use_gtids='0'
    ERROR: _saved_gtids=''
    ERROR: _saved_file='master-bin.000001'
    ERROR: _saved_pos='815297'
    ERROR: _saved_channel_name=
    ERROR: timeout='300'
    ERROR: result='-1'
    ERROR: error type: Timeout after 300 seconds.

Analysis
--------
- Could not replicate the problem locally.
- Tested several 'mtr' options to slow down the process, etc, with no
success in replicating the problem.
- Tested some visible points of failure:
  . Heap max limit exceeded with ENGINE=MEMORY,
  . Inserting 2000 records and synchonize might take more than 300 secondsm
  . I/O thread stops,
  but would fail every time and not sporadically.
- Test fails with the --repeat > 1, due to the usage of a --copy_file command
without validation for the existance of such files in the destination dir. The
--copy_file command does not allow file override and files if the destination
files already exist.

Fix
---
- Reduce the amount of records inserted in order to ensure that the timeout interval
isn't, in fact, being reached.
- Add config variables, for:
  * record count, '$row_count'
  * heap size, '$heap_size'
  * record size, '$record_size'.
- Making '$record_count' dependant of the division of the other two variables.
- Replace --copy_file with --copy_files_wildcard, which allow file to be
overwritten

Notes
-----
- '$record_size' may hold any value, it all depends on the amount of records
one whishes to insert in the tables.