BUG#33176377: Contribution by Facebook: Fix race between binlog sender heartbeat timeout
Post-push fix: broken clang build:
sql/rpl_binlog_sender.cc:815:23: error:
lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]

Change-Id: I5bdae1cf92d05c9520c26419ef122b8aa808677e
(cherry picked from commit cfaf22f6dc7ad37af4a11b6227b5cae02e21fb68)