Fix broken build for WITHOUT_SERVER:BOOL=1
Client .so libraries are linked with -Wl,--no-undefined, and got:
mysys/my_thr_init.cc:123: error: undefined reference to 'key_THR_LOCK_heap'
mysys/my_thr_init.cc:145: error: undefined reference to 'key_THR_COND_threads'
...

Fix: expose these static globals even if HAVE_PSI_MUTEX_INTERFACE and
HAVE_PSI_COND_INTERFACE are undefined, since they are used in
my_thread_global_init and my_thread_global_reinit

Change-Id: I1b7d67a8e8a91ff4d748dce40d8aaa5d2f43ca22