WL#8726
- fix warnings detected by -Werror=suggest-attribute=format which
  appear when merging into 5.8

  storage/ndb/src/common/util/BaseString.cpp:506: error: function might
     be possible candidate for 'gnu_printf' format
     attribute [-Werror=suggest-attribute=format]
   return(basestring_vsnprintf(str, size, format, ap));
                                                    ^
 - most of these are because there was previoulsy no format
   attributes on 'vsnprint' style functions, but it's possible
   to add also for those by setting the third arg to zero.
 - macros which expand strings into one of these functions
   needed to be moved after the function declaration.
 - it was not possible to add format attributes on function
   definitions so some static functions now got a new
   forward declaration where the attribute format could be done