Bug#35078721 - Compilation error in tls_server_context.cc with Clang-13 and OpenSSL < 1.1.0
Problem:
Compilation in debug mode with clang-13 fails due to:

 router/src/harness/src/tls_server_context.cc:62:15: error: unused variable 'kMaxSecurityLevel' [-Werror,-Wunused-const-variable]
 constexpr int kMaxSecurityLevel{5};
               ^

Solution:
Surround the declaration of 'kMaxSecurityLevel' with:

 #if OPENSSL_VERSION_NUMBER >= ROUTER_OPENSSL_VERSION(1, 1, 0)
 constexpr int kMaxSecurityLevel{5};
 #endif

since it is only used in that case.

Change-Id: I8aba47d7d854bb7239c4c9824d30c85511ec8b84