Bug #27034449 MYSQL ROUTER FAILS TO BOOTSTRAP WITH --DIRECTORY WHEN INSTALLED FROM .DEB PKG
The bug is already almost 2 yo and the symptoms are now different:

mysqlrouter  -B 127.0.0.1:5001 --directory=/home/areliga/acx
Please enter MySQL password for root:
Error: Can't use /home/areliga/acx for bootstrap, it is not directory.

The reason is we incorrectly interpret the return value from the mysqlharness::mkdir function that we use
when trying to create a directory.

After the fix the user sees expected error:

mysqlrouter  -B 127.0.0.1:5001 --directory=/home/areliga/acx
Please enter MySQL password for root:
Cannot create directory '/home/areliga/acx': Permission denied
This may be caused by insufficient rights or AppArmor settings.
If you have AppArmor enabled try adding full path to the output directory in the mysqlrouter profile file:
/etc/apparmor.d/usr.bin.mysqlrouter

Example:

/path/to/your/output/dir rw,
  /path/to/your/output/dir/** rw,
Error: Could not create deployment directory

RB: 22137