Fixed PXB-2649 - compilation issues on gcc 10
https://jira.percona.com/browse/PXB-2649

Issue 1:

In file included from /usr/include/c++/10/memory:83,
                 from /work/pxb/src/2.4/storage/innobase/xtrabackup/src/xbcloud/http.h:29,
                 from /work/pxb/src/2.4/storage/innobase/xtrabackup/src/xbcloud/http.cc:21:
/usr/include/c++/10/bits/unique_ptr.h: In instantiation of ‘constexpr std::unique_ptr<_Tp, _Dp>::unique_ptr() [with _Del = std::default_delete<xbcloud::S3_signer>; <template-parameter-2-2> = void; _Tp = xbcloud::S3_signer; _Dp = std::default_delete<xbcloud::S3_signer>]’:
/work/pxb/src/2.4/storage/innobase/xtrabackup/src/xbcloud/s3.h:177:32:   required from here
/usr/include/c++/10/bits/unique_ptr.h:270:9: error: no matching function for call to ‘std::__uniq_ptr_data<xbcloud::S3_signer, std::default_delete<xbcloud::S3_signer>, true, true>::__uniq_ptr_data()’
  270 |  : _M_t()
      |         ^
/usr/include/c++/10/bits/unique_ptr.h:210:40: note: candidate: ‘std::__uniq_ptr_data<xbcloud::S3_signer, std::default_delete<xbcloud::S3_signer>, true, true>::__uniq_ptr_data(std::__uniq_ptr_impl<xbcloud::S3_signer, std::default_delete<xbcloud::S3_signer> >::pointer) [inherited from std::__uniq_ptr_impl<xbcloud::S3_signer, std::default_delete<xbcloud::S3_signer> >]’
  210 |       using __uniq_ptr_impl<_Tp, _Dp>::__uniq_ptr_impl;
      |                                        ^~~~~~~~~~~~~~~

Fix:
Adjusted cmake/build_configurations/compiler_options.cmake to remove
fabi-version if gcc version higher than 9.

Issue 2:
/usr/bin/ld: CMakeFiles/xbstream.dir/xbstream.c.o:/work/pxb/src/2.4/storage/innobase/xtrabackup/src/xbstream.c:61: multiple definition of `datasink_buffer'; CMakeFiles/xbstream.dir/ds_buffer.c.o:(.data.rel.local+0x0): first defined here

Fix:
Removed duplicate declaration.

Issue 3:
/usr/bin/ld: ../../../../archive_output_directory/libmysqld.a(lib_sql.cc.o):(.bss+0x2940): multiple definition of `mysql_tmpdir_list'; CMakeFiles/xtrabackup.dir/ds_tmpfile.c.o:/work/pxb/src/2.4/storage/innobase/xtrabackup/src/ds_tmpfile.c:58: first defined here

Fix:
Renamed mysql_tmpdir_list.