Bug #29682193: OVERLAPS OPERATOR NOT WORKING IN MYSQLX.CRUD.FIND FOR THE TABLE DATA MODEL
Description:
The OVERLAPS operator in the DevAPI is meant to be the interface for the
JSON_OVERLAPS(...) function which is meant to work properly when the
provided operands are JSON data.
It seems this is not the case when using it in a Table.select()
operation that meets the above conditions as I get:
ERROR: 5154: OVERLAPS expression requires identifier that produce a JSON
value.

RB: 22046
Reviewed-by: Tomasz Stepniak <tomasz.s.stepniak@oracle.com>
Reviewed-by: Lukasz Kotula <lukasz.kotula@oracle.com>

Change-Id: Id00d4fa9f55bb1f11bfc3b25cad9d93bc37d8105