BUG#32766981: IMPROVE VISIBILITY ON THE ONGOING OPERATION WHILE ADDING A NEW NODE
Post-push fix for broken build:
error: cannot pass object of non-trivial type
'const std::basic_string<char>' through variadic method;
call will abort at runtime [-Wnon-pod-varargs]

Change-Id: I684d44fdac47944d644a69db7208323bdf75d1c4
(cherry picked from commit a48097b1ee47919ba285e5b3c66e213b83112272)