Bug #34384889 Fix misc warnings in ndbcluster
Fix storage/ndb warnings for cmake -DWITH_VALGRIND=1
(building in RelWithDebInfo mode)

When building unit test ndb_zlib: -Werror=maybe-uninitialized

storage/ndb/src/common/transporter/TransporterRegistry.cpp:1302:45: error:
ptr may be used uninitialized [-Werror=maybe-uninitialized]

storage/ndb/src/ndbapi/NdbImpl.hpp -Werror=unused-parameter

Change-Id: I70c937946e57432e378dbf71efcd541e080279a1
(cherry picked from commit 762392f63017b84ef250fc29d9f030d287f800f2)