BUG#33405699: After secondary node is killed, it can not rejoined
Post-push fix:
fbgc_ticket.h:54:26: error: uint64_t in namespace std does not name a type;
did you mean wint_t?

Change-Id: Ibcb3d489b6b9b5d9df788fb1d2f7e1de8a8570bb
(cherry picked from commit 5ba367560d001a288a5a009ce291e6837aeecd17)