Bug#26436968 SWITCH TO DEVTOOLSET 6 FOR EL6 AND EL7 FOR MYSQL 8.0
Extra patch for
WL#9509 - X Protocol connector code extraction from mysqlxtest to libmysqlxclient

Fixes warning for gcc 6.2 on linux/sparc:
message_field_chain.cc.o Error 1
extra/protobuf/protobuf-2.6.1/src/google/protobuf/stubs/atomicops_internals_generic_gcc.h
inline Atomic32 Acquire_CompareAndSwap(volatile Atomic32* ptr,
error: parameter 'ptr' set but not used

Change-Id: I691bbf6e87e41ff44b5b38c225c65add2f890eb5