Bug#34667901 GCC 12 FORMAT-OVERFLOW ERROR ON NDB_TEST
Increase buffer length to accomodate char array written with sprintf.
Max is for "t%dx%d" size, 10 * 2 for %d, 1 for t and x and another for
\0 (23 total); thus raising to 32.

Errors:
error: ‘%d’ directive writing between 1 and 10 bytes into a region of size 9 [-Werror=format-overflow=]
10704 |     sprintf(dt.tabname, "t%d", i);
note: ‘sprintf’ output between 3 and 12 bytes into a destination of size 10
10704 |     sprintf(dt.tabname, "t%d", i);

error: ‘%d’ directive writing between 1 and 10 bytes into a region of size 9 [-Werror=format-overflow=]
10729 |       sprintf(di.indname, "t%dx%d", i, 1);
note: ‘sprintf’ output between 5 and 14 bytes into a destination of size 10
10729 |       sprintf(di.indname, "t%dx%d", i, 1);

error: ‘%d’ directive writing between 1 and 10 bytes into a region of size 9 [-Werror=format-overflow=]
10709 |       sprintf(dc.colname, "%c%d", 'a' + j, i);
note: ‘sprintf’ output between 3 and 12 bytes into a destination of size 10
10709 |       sprintf(dc.colname, "%c%d", 'a' + j, i);

Change-Id: I8e559fcdcf9986a05fdd22c2d6e4c8829d0af52a