Bug #32910699 BROKEN BUILD DUE TO UT_DELETE
Recent change in trunk (b23250f72c38) introduced ut_delete call
(ddl/ddl0fts.cc). Using ut_delete symbol in builds that disable PFS
memory tracing (e.g. with -DDISABLE_PSI_MEMORY=ON) will render those
builds as failed.

storage/innobase/ddl/ddl0fts.cc: In member function ‘dberr_t ddl::FTS::Parser::enqueue(ddl::FTS::Doc_item*)’:
storage/innobase/ddl/ddl0fts.cc|397 col 7| error: ‘ut_delete’ was not declared in this scope; did you mean ‘rbt_delete’?
   397 |       ut_delete(doc_item);
       |       ^~~~~~~~~
       |       rbt_delete
 ninja: build stopped: subcommand failed.

One must use UT_DELETE macro instead. ut_delete is supposed to be an
implementation detail but because it exists in the same (public) header
it is easy to confuse the usages and pick the wrong one.

Soon to come patch which overhauls ut0new implementation will make this
situation less likely so this patch fixes the consequence only.

Reviewed-by: Kuba Lopuszanski <jakub.lopuszanski@oracle.com>