Bug#30990567 -WUNUSED-PARAMETER SRC_SIZE WITH ZSTD < 1.4
Problem
-------

building with libzstd < 1.4 and -Werror fails the build with:

  plugin/x/protocol/stream/compression/compression_algorithm_zstd.h:56:42:
  error: unused parameter 'src_size' [-Werror,-Wunused-parameter]
    void set_pledged_source_size(const int src_size) override {
                                           ^

Change
------

- marked src_size parameter with "unused"-attribute

RB: 24023