Bug#37721464 Compile MySQL with GCC 15 [innodb noclose]
storage/innobase/lock/lock0lock.cc:1182:11:error:
'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct ib_lock_t';
use assignment
 instead [-Werror=class-memaccess]
 1182 |     memset(&lock[1], 0x0, size);

Use lock_rec_bitmap_reset() rather than memset() to reset lock structs.

Change-Id: Ia540fe2d9abb0f9cbbe72e4624a20853d6d23a80
(cherry picked from commit db9abb0ddb6a656cc5aefe78c6fced02be3d1abd)
(cherry picked from commit 981a8349b40927f281eef3895184a28e8dd70842)