Bug #34278103 Compile MySQL with GCC 13 [noclose]
Fix more warnings from gcc 13:

sql/changestreams/apply/commit_order_queue.cc:119:29:   required from here
sql/memory/unique_ptr.h:784:63: error:
moving a temporary object prevents copy elision [-Werror=pessimizing-move]
  784 |   return std::move(memory::Unique_ptr<T, std::nullptr_t>{size});
      |                                                               ^
sql/memory/unique_ptr.h:784:63: note: remove ‘std::move’ call

unittest/gunit/memory/unique_ptr-t.cc:88:46:   required from here
sql/memory/unique_ptr.h:804:73: error:
moving a temporary object prevents copy elision [-Werror=pessimizing-move]
  804 |       memory::Unique_ptr<T, std::nullptr_t>{std::forward<Args>(args)...});
      |                                                                         ^
sql/memory/unique_ptr.h:804:73: note: remove ‘std::move’ call

building meb_innodb
storage/innobase/include/mach0data.ic:106:8:
error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  106 |   b[0] = (byte)(n >> 16);

router/include/mysql/harness/plugin.h:377:22: error:
identifier ‘requires’ is a keyword in C++20 [-Werror=c++20-compat]
  377 |   const char *const *requires;

router/src/harness/include/mysql/harness/net_ts/local.h:185:14: error:
redundant move in return statement [-Werror=redundant-move]
  185 |   const auto fds = std::move(*res);

router/src/harness/tests/plugins/example.cc:61:20: error:
identifier ‘requires’ is a keyword in C++20 [-Werror=c++20-compat]
   61 | static const char *requires[] = {

router/src/mysql_protocol/tests/../include/mysqlrouter/classic_protocol_codec_message.h:1214:16:
error: moving a temporary object prevents copy elision [-Werror=pessimizing-move]
 1214 |     const auto nullbits = std::move(nullbits_res->value());

router/src/plugin_info/src/plugin.h:59:16: error:
identifier ‘requires’ is a keyword in C++20 [-Werror=c++20-compat]
   59 |   const char **requires;

router/src/routing/src/classic_frame.cc:201:27: error:
redundant move in return statement [-Werror=redundant-move]
  201 |       auto hdr = std::move(*hdr_res);

router/src/router/src/router_app.cc:796:31: error:
redundant move in return statement [-Werror=redundant-move]
  796 |     const auto err = std::move(res.error());

Change-Id: Idcc8a61c9f11031c7a6d94f705aa0ba304cda457