Bug#34379235 duplicated hexify()
Post-push fix for broken build with gcc 13.0.0

include/hexify.h:47:42: error:
ISO C++ forbids declaration of type name with no type [-fpermissive]
einterpret_cast<const uint8_t *>

Change-Id: I5b506cd8293975f33ec8d3eebcaafa5aaa434d93
(cherry picked from commit 30de6e96d17fecb412f31e106a771a743876875d)