Bug#29167178: FIX CLANG 8 WARNINGS
Clang 8 reports warnings of this kind:

  error: adding 'int' to a string does not append to the string
  [-Werror,-Wstring-plus-int]

Take the address of the first character of the substring instead of
adding the offset to the literal to make it clearer to the compiler
that it is not an attempt to append to the string.

Change-Id: I4ac921556737f9dbcc8e08518c2fa83892fd7582